[package]
name = "antech-kdf"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
antech-kdf-types = { workspace = true }
antech-kdf-core = { workspace = true }

[dev-dependencies]
antech-kdf-core = { workspace = true }
antech-kdf-format = { workspace = true }
antech-kdf-types = { workspace = true }
rand = { workspace = true }
